http:
  routers:
    homeassistant:
      rule: "Host(`ha.markcheli.com`)"
      entryPoints:
        - websecure
      service: homeassistant-service
      middlewares:
        - homeassistant-headers
      priority: 1000
      tls: {}

  services:
    homeassistant-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.121:8123"

  middlewares:
    homeassistant-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-For: ""
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true